version: "3.7"

services:
  vapi:
    image: ecency/api:latest
    environment:
      - PRIVATE_API_ADDR=${PRIVATE_API_ADDR}
      - PRIVATE_API_AUTH=${PRIVATE_API_AUTH}
      - HIVESIGNER_SECRET=${NEXT_PUBLIC_HIVESIGNER_SECRET}
      - SEARCH_API_ADDR=${SEARCH_API_ADDR}
      - SEARCH_API_SECRET=${SEARCH_API_SECRET}
    deploy:
      restart_policy:
        condition: any
    ports:
      - "4000:4000"
    hostname: vapi
    networks:
      - vision
    security_opt:
      - seccomp=unconfined

  web:
    image: ecency/vision-next:develop
    environment:
      - NEXT_PUBLIC_USE_PRIVATE=${NEXT_PUBLIC_USE_PRIVATE}
      - NEXT_PUBLIC_HIVESIGNER_SECRET=${NEXT_PUBLIC_HIVESIGNER_SECRET}
    deploy:
      restart_policy:
        condition: any
    ports:
      - "3000:3000"
    hostname: web
    networks:
      - vision
    security_opt:
      - seccomp=unconfined

networks:
  vision:
    external: true
